export const EXAMPLE_PROMPTS: string[] = [
  "Urban Development through DeFi",
  "AI and Web3 for Social Good",
  "Global Accessibility via Web3 Education",
  "Stablecoin Adoption",
  "Regenerative Farming",
  "Renewable Energy for Communities",
  "Environmental Tech Innovations",
  "Digital Art for the Environment",
  "Open Source Software",
  "Forestry and Blockchain",
  "Blockchain for SDGs",
  "Social Impact Innovations in Decentralized Gaming",
  "Climate Action with DeSci",
  "Digital Community Platforms",
  "Supply Chain Transparency and Accountability",
  "DAOs",
  "Blockchain for Social Impact",
  "Web3 for Biodiversity and Conservation",
  "Local Economies Using Cryptocurrency Solutions",
  "Digital Transformation in Education",
  "Innovations in NFT Marketplaces",
  "Blockchain Transforming Healthcare",
  "Expansion Strategies for DeFi Protocols",
  "Wallet Security",
  "Tokenomics: Research and Development",
  "Sustainable Cryptocurrency Mining",
  "Blockchain Games",
  "Crypto Philanthropy",
  "Agricultural Advancements through Blockchain",
  "Decentralized Exchanges",
  "Blockchain and Renewable Energy",
  "Financial Inclusion through DeFi Innovations",
  "Web3 for Learning",
  "Decentralized Data Storage",
  "Blockchain-Enabled Digital Identities",
  "ReFi Projects Driving Climate Solutions",
  "Environmental Actions with NFTs",
  "Longevity and Web3",
  "Decentralized Science Communities",
  "Blockchain Privacy",
  "Cross-Chain Asset Management Solutions",
  "AI in Governance",
  "Smart Cities with Blockchain",
  "Collaborative Projects in Social Impact DeSci",
  "Podcasts on Blockchain Technology",
  "Bridging Bounties to Enhance Project Progression",
  "dApp Development",
  "Local Eco-Projects",
  "Ethereum Staking",
  "Open-Access Research Platforms in Decentralized Science",
  "Data Analysis Techniques in Web3",
  "Account Abstraction",
  "Smart Contract Tools",
  "Strategies for DeFi Market Expansion",
  "Privacy Technologies",
  "Social Impact Initiatives in Africa",
  "Eco-Initiatives and Environmental Projects in Southeast Asia",
  "Environmental Initiatives",
  "Multichain Interoperability for Blockchain",
  "Blockchain Security Technologies",
  "Digital Identity Solutions for Refugees",
  "Token Standards",
  "Solutions for Ethereum Scalability Challenges",
  "Applications of Zero-Knowledge",
  "Global Payment Systems",
  "EIPs on Ethereum Ecosystem",
  "Growth Strategies for the NFT Ecosystem",
  "Crypto Economics",
  "Coordination Tools for Effective Communal Living",
  "Innovations in DeFi on Arbitrum",
  "Climate Change Tokens",
  "Cross-Chain DeFi",
  "Integrating NFTs within Decentralized Science (DeSci)",
  "Tokenizing Assets",
  "Cryptographic Privacy Enhancements",
  "Asset Liquidity through Tokenization",
  "Eco-Friendly Blockchain",
  "Crypto Adoption and Its Impact in Latin America",
  "DeFi and Regulation",
  "Network States",
  "Ethereum Infrastructure",
];
