export const EXAMPLE_PROMPTS = [
  "Urban Regeneration with DeFi Solutions",
  "Impact Verification through Open-Source AI and Web3",
  "Global Accessibility via Web3 Education",
  "Stablecoin Adoption",
  "Ecosystem Revival through Regenerative Agriculture Practices",
  "Resilient Communities via Renewable Energy Projects",
  "Ecological Monitoring Innovation",
  "Digital Art for Environmental Advocacy",
  "Open Source Software",
  "Advancing Forestry Conservation via Blockchain",
  "Social Impact Innovations in Decentralized Gaming",
  "Climate Solutions through DeSci",
  "Digital Inclusion through Community-Driven Platforms",
  "DAO Governance Structures",
  "Blockchain's Role in Achieving Sustainable Development Goals (SDGs)",
  "Blockchain for Social Impact",
  "Biodiversity Enhancement with Web3 Initiatives",
  "Local Economies Using Cryptocurrency Solutions",
  "Digital Transformation in Education",
  "Innovations in NFT Marketplaces",
  "Expansion Strategies for DeFi Protocols",
  "Enhancing Crypto Wallet Security",
  "Integrating Blockchain into Educational Systems",
  "Tokenomics: Research and Development",
  "Multichain Interoperability for Seamless Transactions",
  "Sustainable Cryptocurrency Mining",
  "Healthcare with Blockchain",
  "Smart Contract Development and Innovation",
  "Platforms in Blockchain Gaming",
  "Models for Crypto Philanthropy and Social Good",
  "Ensuring Privacy within Blockchain Technologies",
  "Agricultural Advancements through Blockchain",
  "Enhancing Supply Chain Transparency and Accountability",
  "Integrating NFTs within Decentralized Science (DeSci)",
  "Decentralized Exchanges",
  "Renewable Energy Projects on the Blockchain",
  "Financial Inclusion through DeFi Innovations",
  "Web3 Initiatives for Broadened Educational Opportunities",
  "Decentralized Data Storage",
  "Blockchain-Enabled Digital Identities",
  "ReFi Projects Driving Climate Solutions",
  "Open-Access Research Platforms in Decentralized Science",
  "Web3's Role in Longevity Research",
  "Conservation Efforts and Biodiversity through Blockchain",
  "Fostering Communities in Decentralized Science",
  "Cross-Chain Asset Management Solutions",
  "AI in Decentralized Governance",
  "Blockchain as a Tool for Sustainable Cities",
  "Collaborative Projects in Social Impact DeSci",
  "Podcasts on Blockchain Technology",
  "Bridging Bounties to Enhance Project Progression",
  "Coordination Tools for Effective Communal Living",
  "dApp Development",
  "Environmental Actions with NFTs",
  "Supporting Local Regenerative Projects for Ecosystem Health",
  "Ethereum Staking",
  "Data Analysis Techniques in Web3",
  "Account Abstraction",
  "Visual Tools for Managing Smart Contracts",
  "Strategies for DeFi Market Expansion",
  "Privacy Technologies",
  "Social Impact Initiatives in Africa",
  "Eco-Initiatives and Environmental Projects in Southeast Asia",
  "Environmental Initiatives",
  "Multichain Interoperability for Blockchain",
  "Blockchain Security Technologies",
  "Digital Identity Solutions for Refugees",
  "Solutions for Ethereum Scalability Challenges",
  "Impactful EIP Proposals on the Ethereum Ecosystem",
  "Standards for Cross-Chain Token Interoperability",
  "Applications of Zero-Knowledge",
  "Global Payment Systems",
  "Growth Strategies for the NFT Ecosystem",
  "Innovations in DeFi on Arbitrum",
  "Climate Change Tokens and Their Impact",
  "Protocols for Cross-Chain DeFi Efficiency",
  "Exploration of Cryptoeconomic Models",
  "Real-World Asset Tokenization Strategies",
  "Cryptographic Privacy Enhancements",
  "Asset Liquidity through Tokenization",
  "Energy Efficiency in Blockchain Technologies",
  "Crypto Adoption and Its Impact in Latin America",
  "DeFi Regulatory Compliance Challenges",
  "Blockchain in Network States",
  "Ethereum Infrastructure"
];
