export const EXAMPLE_PROMPTS: string[] = [
"Privacy tech",
"ZK scaling solutions",
"Environmental conservation in Africa",
"Account abstraction",
"EIPs",
"EVM dev tools",
"Better governance mechanisms",
"Academic research",
"Art",
"Node monitoring software",
"NFT tech",
"Social impact in South America",
"Agroforestry and permaculture",
"ReFi",
"DAO tooling",
"Mutual credit and community currencies",
"Impact certificates and impact evaluation frameworks",
"AI agents for good",
"Longevity",
"AI safety",
"Blockchain law",
"Smart cities",
"Data analysis tools",
"Crypto content creators",
"Renewable energy projects",
"Decentralized identity solutions",
"Financial inclusion",
"Water purification technologies",
"Digital rights and internet freedom",
"Public health",
"Space exploration",
"Human rights advocacy",
"Supply chain transparency",
"Indigenous communities",
"Open source alternatives",
"Ocean conservation and marine life protection",
"Wildlife preservation and anti-poaching efforts",
"Gender equality and women's empowerment",
"Smart contract auditing and security tools",
"Wallet UX",
"Crypto accounting tools",
"Network States",
"Global south crypto initiatives",
"Web3 educational resources",
"Ethereum community events",
"Cross-chain bridging tech",
"Ethereum L2 ecosystem",
"Interchain",
"Crypto legal defense",
"Decentralized messaging and social networks",
"Decentralized raves",
"Decentralized housing",
"Token engineering",
"Mechanism design",
];
